### ISSUE TITLE
Feature requests: changing calendar in an event

### ISSUE THREAD

**Issue by gerhardbeck** [Etar-Group/Etar-Calendar#399] opened 2018-11-18 23:56 UTC
I use several calendars and sometimes create events in the wrong calendar. Would be great if there would be a Chance to correct it, e.g. changing a calendar when changing an events details

**Comment by ramack** [comment] 2018-11-19 05:40
That would be great, yes!

**Comment by jspricke** [comment] 2018-11-19 06:38
Duplicate of #101

**Closed by jspricke** 2018-11-19 06:38 UTC
