### ISSUE TITLE
Cannot update F-droid

### ISSUE THREAD

**Issue by coffseducation** [Etar-Group/Etar-Calendar#1454] opened 2023-09-26 11:06 UTC
Cannot update to version 1.0.35 in F-Droid.

"Error installing Etar - OpenSource Calendar

Error -112: The system failed to install the package because it is attempting to define a permission that is already defined by some existing package."

**Comment by jspricke** [comment] 2023-09-26 11:10
Duplicate of #1438

**Closed by jspricke** 2023-09-26 11:10 UTC
