### ISSUE TITLE
Widget Dark Theme

### ISSUE THREAD

**Issue by GiiantWaffle** [Etar-Group/Etar-Calendar#329] opened 2018-05-29 21:08 UTC
Nice Calendar!  Thanks!

WIDGET: Dark Theme???

**Comment by charlescrammond** [comment] 2018-06-25 13:10
+1
Love the Calender widget, please in dark without the black border, so its seamless. Warm thoughts.

**Comment by jancborchardt** [comment] 2018-07-02 08:12
This is a duplicate of issue #190. @GiiantWaffle could you close this? Then let's continue there. :)

**Closed** 2018-07-02 08:13 UTC
