### ISSUE TITLE
Event creation leaves a duplicate event when Android's foreground is interrupted by another app

### ISSUE THREAD

**Issue by KeronCyst** [Etar-Group/Etar-Calendar#265] opened 2017-10-21 17:07 UTC
1. Start adding details to a new calendar event, but don't save anything about it. Stay on the editing page
2. Let the screen get interrupted by an app that takes over the foreground, like an alarm or something
3. Once you deal with that and return to Etar, the current page will actually be for a new unsaved event. So if you save this one, the calendar will show two copies of the event.

#3 should open the original event, not a copy.

**Comment by smichel17** [comment] 2017-10-21 17:47
Duplicate of #216

**Closed** 2017-10-21 17:49 UTC
