### ISSUE TITLE
Feature request: move event to other calendar

### ISSUE THREAD

**Issue by mgw2013** [Etar-Group/Etar-Calendar#1410] opened 2023-06-12 16:32 UTC
Unfortunately, we have to maintain several agendas i. e. several calendars sync'ed via DAVX5. Sometimes it happens that an event is opened by the user in a wrong calendar.

Etar does not allow to move this event to another calendar. So either the event must be deleted and copied/re-typed into the correct calendar or users use their Laptop app (in our case Thunderbird).

**Comment by wilhelmy** [comment] 2023-07-16 13:12
I'm a big fan of Etar Calendar so far but this feature is definitely missing

**Comment by wilhelmy** [comment] 2023-07-16 13:13
Issue seems to be a duplicate of #62 though

**Comment by Tianonymus** [comment] 2023-10-25 05:52
FYI Events can be duplicated from the top right menu when an event has been selected. There, another calendar can be chosen. The previous event has to be deleted manually, though.

**Comment by mgw2013** [comment] 2023-10-26 13:18
I see - request from 2016... ?

**Closed** 2024-06-10 17:50 UTC
