### ISSUE TITLE
How can i activate this function?

### ISSUE THREAD

**Issue by Comprehensible7** [Etar-Group/Etar-Calendar#614] opened 2020-01-03 11:21 UTC
Hi!

I'd like to know how can I activate this function

it`s kind of due day

and I want to put in this function on this calendar

here is the Picture

I want to activate the function using the checkbox and have it appear on the calendar.

How is it possible to operate?

Thanks

<img width="379" alt="Screenshot 2020-01-03 at 8 19 58 PM" src="https://user-images.githubusercontent.com/57204545/71720868-77393080-2e66-11ea-8951-ddf61b42a9c9.png">

**Comment by jspricke** [comment] 2020-01-03 11:32
Duplicate of #83 
There is no model to implement this into a `VEVENT`.

**Closed by jspricke** 2020-01-03 11:32 UTC
