### ISSUE TITLE
Week number wrong for first week of year

### ISSUE THREAD

**Issue by bartlibert** [Etar-Group/Etar-Calendar#1553] opened 2024-01-06 11:10 UTC
For the first week of the 2024, the week number is not displayed correctly. Instead of "week 1”, I see " week <xliff:g ...".

![Screenshot_20240106-120308](https://github.com/Etar-Group/Etar-Calendar/assets/948770/8e18e9d3-d40f-4006-9d56-2a944f644f34)

This is with Etar 1.0.38 on Android 14, in Dutch.

**Comment by jspricke** [comment] 2024-01-06 11:12
Duplicate of #1545

**Closed by jspricke** 2024-01-06 11:12 UTC
