### ISSUE TITLE
Very good, I want every custom ROM use it, but here's one thing

### ISSUE THREAD

**Issue by fufik** [Etar-Group/Etar-Calendar#577] opened 2019-10-26 15:31 UTC
A wondeful app you made, yet I would fancy some widgets as well. Like those from stock calendar or Google one. =)

**Comment by PanderMusubi** [comment] 2019-12-06 06:54
https://github.com/Etar-Group/Etar-Calendar/issues/417

**Comment by jspricke** [comment] 2020-01-03 11:37
Duplicate of #417

**Closed by jspricke** 2020-01-03 11:37 UTC
