### ISSUE TITLE
Dynamic Icon?

### ISSUE THREAD

**Issue by MatthK** [Etar-Group/Etar-Calendar#1253] opened 2022-11-02 08:27 UTC
I just came across your app and it looks really promising.

It's not an issue, more a feature request. Would it be possible to make the app icon dynamic in terms that instead of showing the "30" in the calendar, displaying the actual day of the month. So today it would be a "2", tomorrow a "3", etc.

**Comment by jspricke** [comment] 2022-11-02 08:30
Duplicate of #711

**Closed by jspricke** 2022-11-02 08:30 UTC
