### ISSUE TITLE
Editing an all-day event makes it a day longer.

### ISSUE THREAD

**Issue by jtagcat** [Etar-Group/Etar-Calendar#1173] opened 2022-06-01 15:58 UTC
1. Create an all-day event for any day, let's pick 2. june.
2. On calendar views, it is shown only on 2nd. While the text says 2nd-3rd.
3. Editing it, dates are 2nd-3rd.
4. Editing it again, dates are 2nd-4th.

While editing, toggling all-day changes day by one.

**Comment by Parsnip** [comment] 2022-07-01 10:25
I was just coming to report this. Every time you open an all day event for editing, the end date gets incremented by one. Even if you back out of the edit interface with the android back button, the new unintentionally incremented end date is saved.

This only happens with all day events as far as I've seen.

**Comment by TOMats3** [comment] 2022-07-18 22:20
Agree. I would add that on screen with event details / description, start date is put one day back.
To sum up:
Day / week / month / agenda screen: OK
Event details screen: start day -1 day
Event edit screen: end day +1 day

**Comment by lmamane** [comment] 2023-06-04 11:09
I remember I used to encounter this, but don't anymore. This might be because my system timezone (not app-specific home timezone) is UTC.

**Comment by lmamane** [comment] 2023-06-04 16:34
Could be fixed by GH-1405, not sure. Let me know.

**Comment by Parsnip** [comment] 2023-10-06 12:18
> Could be fixed by [GH-1405](https://github.com/Etar-Group/Etar-Calendar/pull/1405), not sure. Let me know.

I only just now noticed the update and it's fixed indeed, I at least can no longer reproduce any odd behavior with all day events. Great work! 👍❤️

**Comment by IamJeffG** [comment] 2023-10-07 00:03
> I only just now noticed the update and it's fixed indeed, I at least can no longer reproduce any odd behavior with all day events on my timezone

Same observation, this seems to be fixed for me right now too.  :+1:

**Closed** 2024-01-19 19:07 UTC
