### ISSUE TITLE
Update and reinstallation not possible

### ISSUE THREAD

**Issue by coleltr** [Etar-Group/Etar-Calendar#1682] opened 2024-06-16 09:05 UTC
I got the following message when I first tried to update to 1.0.46, and also after I deinstalled the app an tried to install it again:

INSTALL_FAILED_DUPLICATE_PERMISSION: Package ws.xsoh.etar attempting to redeclare permission ws.xsoh.etar.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION already owned by org.lineageos.etar

**Comment by coleltr** [comment] 2024-06-16 14:11
I didn't realize, that etar is already part of lineage os. So it's not necessay to install the app in addition. 
Maybe the error message could point out that fact.

**Comment by jspricke** [comment] 2024-06-16 15:27
Duplicate of #1438, please use this workaround: https://github.com/Etar-Group/Etar-Calendar/issues/1438#issuecomment-1787246603

**Closed by jspricke** 2024-06-16 15:27 UTC
