### ISSUE TITLE
Make new release with per-event colour support

### ISSUE THREAD

**Issue by dilyanpalauzov** [Etar-Group/Etar-Calendar#384] opened 2018-10-10 06:39 UTC
A new release will force peope to install eTar on Android, if the users want to change the event color, because the default calendar on Android does not offer this functionality.  So eTar has a visible feature that the standard calendar on Android lacks.

**Comment by jspricke** [comment] 2018-10-10 08:04
Duplicate of #362.

**Closed by jspricke** 2018-10-10 08:04 UTC
