### ISSUE TITLE
Create event dialog disappears when the orientation of the device is changed

### ISSUE THREAD

**Issue by Atalanttore** [Etar-Group/Etar-Calendar#673] opened 2020-03-20 21:38 UTC
The Create event dialog disappears when the orientation of the device is changed.

## Steps to reproduce
1. Open the create event dialog
2. Change the orientation of the device

**Comment by jspricke** [comment] 2020-03-20 21:40
duplicate of #563

**Closed by jspricke** 2020-03-20 21:40 UTC
