### ISSUE TITLE
Mute alarms from specific calendar

### ISSUE THREAD

**Issue by Kalytis** [Etar-Group/Etar-Calendar#1138] opened 2022-04-06 22:09 UTC
Nextcloud's birthday calendar pops up a notification at midnight. It's pissing off, especially on my phone.

I was so sure there was a way to disable alarms for a whole calendar. I thought I had no alarms for my birthday calendars before, but since the last update, I have them again, and can't find a way to block them.

Thanks a lot for your help.

**Comment by Zocker1999NET** [comment] 2022-07-01 12:39
might be related to #1107

**Comment by niccokunzmann** [comment] 2022-10-13 12:45
I think, this is a duplicate of #1107.

**Comment by akki42** [comment] 2024-01-10 20:31
This has been requested / discussed for years. Please see https://github.com/Etar-Group/Etar-Calendar/issues/67 and https://github.com/Etar-Group/Etar-Calendar/issues/783.

**Closed** 2024-02-01 01:20 UTC
