### ISSUE TITLE
Build not successful

### ISSUE THREAD

**Issue by ferguquang** [Etar-Group/Etar-Calendar#586] opened 2019-11-01 03:23 UTC
I tried to get your sourcecode, but when the build failed, an error occurred:
ERROR: Cannot read packageName from Q:\Android\Calendar2\Etar-Calendar\external\timezonepicker\src\main\AndroidManifest.xml
Package "external" has problem?
Help me, thank you!

**Comment by jspricke** [comment] 2019-11-01 06:57
Please read the build instructions here: https://github.com/Etar-Group/Etar-Calendar#build-instructions
Sounds like you are missing the `git submodules` step.
Closing as not a bug.

**Closed by jspricke** 2019-11-01 06:57 UTC
