### ISSUE TITLE
Event changes to the day before on edit

### ISSUE THREAD

**Issue by liperibeiro** [Etar-Group/Etar-Calendar#1164] opened 2022-05-20 14:30 UTC
When I edit an event, I noticed the date is changed to the day before. I always have to remember to set the right date again before saving any change.
How to reproduce it:
1. Click on an event on the calendar
2. Click the pencil icon to edit it
At this point, in the Edit screen, the date is set to the day before. Let's say the event date was 05/25. When the edit screen opens it is set to 05/24.
I'm using v. 1.0.30 on Android 11

**Comment by prg318** [comment] 2022-07-15 17:25
I've also experienced this frequently with the latest version of etar and android 11

**Comment by jspricke** [comment] 2022-07-15 17:54
Can't reproduce on Android 12

**Comment by aereaux** [comment] 2022-08-24 02:53
I have a very reproducible, very similar issue, looks like #1173.  Is it possible it's a timzone issue or something?  Is there any debugging info I can provide?

**Comment by glemco** [comment] 2022-08-24 16:15
I can confirm it is a timezone issue, but the results are a little misleading (I didn't inspect the code much).
I tested with an all day event for the 18th of August with different time zones. Here are the results.
```
Created the event (all the same)
Begin 18th august - End 18th August
Viewing the event
Negative time zone: Begin 18th august - End 19th August
Positive time zone: Begin 17th august - End 18th August
Zero time zone: Begin 18th august - End 18th August
Editing the event
Negative time zone: Begin 18th august - End 19th August
Positive time zone: Begin 18th august - End 19th August
Zero time zone: Begin 18th august - End 18th August
```
As you can see the only case in which the event stays correct both viewing and editing is with a UTC time zone, the event looks as lasting 2 days if viewing in both plus and minus time zones, but with different offset. Editing the event causes the end to move for both in the same direction (saving without modifying makes the event last one more day).
Besides the untriggered modification mentioned above, in all cases changing the event from all-day to normal increases the end by a further day (e.g. 19th if UTC and 20th August otherwise)

Extended AOSP 12, etar 1.0.30 fdroid

**Comment by Parsnip** [comment] 2022-10-20 14:07
Is there any hope that this might get fixed since it seems the underlying issue is known? Etar seems to be one of the few if not the only calendar that has colored event support on non google accounts (e.g. through davx5) so it would be a shame to give that up.

**Comment by glemco** [comment] 2022-10-22 05:51
Unfortunately I'm not entirely sure the underlying issue is known. I'm running another android version (AICP 17.1, android 12.1) and it seems it's fixed for my time zone. Curiously enough if i put negative time zones, events are going backwards (still one day but the previous, in contrast with what I previously observed).
Again I'm giving a free guess: perhaps the app is relying on some undefined behaviour of the library and different implementations work differently. Unfortunately I have no time to check the code and make sure of this..

**Comment by Parsnip** [comment] 2022-10-22 21:48
Ah, I assumed the timezone stuff was for sure the cause. For what its worth, I grabbed the previous version 1.0.29 from f-droid and it doesn't have this problem on my end. This is on Moto G200 5G and Android 12. Sadly I don't have the ability to test specific commits to be sure where it happened but all the Android 12 Time API changes in PR #1047 does seem like a good candidate.

**Comment by lmamane** [comment] 2023-06-04 16:31
It this is only about all-day events, then probably fixed by GH-1405. Let me know.

**Closed** 2024-01-19 14:03 UTC
