### ISSUE TITLE
Download .apk from github directly with Obtainium

### ISSUE THREAD

**Issue by HomemadeAdvanced** [Etar-Group/Etar-Calendar#1604] opened 2024-03-07 17:41 UTC
I would like to pull the latest .apk directly from github using Obtainium. In order to do this, the latest released .apk would have to be listed under Releases. Would this be possible or is there another way to get the latest .apk directly from github?

Thanks in advance.

**Comment by jspricke** [comment] 2024-03-07 18:01
Duplicate of #1274

**Closed by jspricke** 2024-03-07 18:01 UTC
